services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - C:/Users/zaoua/Documents/IoT/volumes/mongo-data:/data/db
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto/config
      - C:/Users/zaoua/Documents/IoT/volumes/mosquitto-data:/mosquitto/data
      - C:/Users/zaoua/Documents/IoT/volumes/mosquitto-logs:/mosquitto/log
    restart: unless-stopped

  bridge:
    build: ./bridge
    container_name: mqtt_to_mongo_bridge
    depends_on:
      - mongo
      - mosquitto
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "3000:3000"
    restart: unless-stopped

  temperature-sensor:
    build: ./temperature-sensor
    environment:
      - TOPIC=sensors/temperature
    depends_on:
      - mosquitto
    restart: unless-stopped
    deploy:
      replicas: 2
