services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - C:/Users/zaoua/Documents/IoT/volumes/mongo-data:/data/db
    restart: unless-stopped
    networks:
      - iot_network

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "8883:8883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto/config
      - ./mosquitto/certs:/etc/mosquitto/certs
      - C:/Users/zaoua/Documents/IoT/volumes/mosquitto-data:/mosquitto/data
      - C:/Users/zaoua/Documents/IoT/volumes/mosquitto-logs:/mosquitto/log
    restart: unless-stopped
    networks:
      iot_network:
        ipv4_address: 192.168.2.10

  bridge:
    build: ./bridge
    container_name: mqtt_to_mongo_bridge
    depends_on:
      - mongo
      - mosquitto
    restart: unless-stopped
    volumes:
      - ./bridge/certs:/app/certs
    networks:
      - iot_network

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - iot_network
    restart: unless-stopped

  temperature-sensor:
    build: ./temperature-sensor
    depends_on:
      - mosquitto
    volumes:
      - ./temperature-sensor/certs:/app/certs
    restart: unless-stopped
    networks:
      - iot_network
    deploy:
      replicas: 1

networks:
  iot_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.2.0/24