services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - C:/Users/zaoua/Documents/IoT/volumes/mongo-data:/data/db
    restart: unless-stopped

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto/config
      - C:/Users/zaoua/Documents/IoT/volumes/mosquitto-data:/mosquitto/data
      - C:/Users/zaoua/Documents/IoT/volumes/mosquitto-logs:/mosquitto/log
    restart: unless-stopped

  bridge:
    build: ./bridge
    container_name: mqtt_to_mongo_bridge
    depends_on:
      - mongo
      - mosquitto
    restart: unless-stopped

  temperature-sensor1:
    build: ./temperature-sensor
    container_name: temperture-sensor1
    environment:
      - TOPIC=sensors/temperature
      - SENSOR_ID=01944130-11a4-73fe-8fb2-913b89fad8ff
    depends_on:
      - mosquitto
    restart: unless-stopped

  temperature-sensor2:
    build: ./temperature-sensor
    container_name: temperture-sensor2
    environment:
      - TOPIC=sensors/temperature
      - SENSOR_ID=01944130-fb36-7fe5-a904-a3478b2f8deb
    depends_on:
      - mosquitto
    restart: unless-stopped